[application]
name = "Video Annotation Tool"
version = "0.3.0"
author = "Zulution.AI"
enable_hashsum_validation = true
enable_video_preprocessing = false

[accept_reasons]
_simple = [
    "略",
]

[reject_reasons]
_simple = [
    "转场、剪辑效果",
    "后期合成字幕",
    "运动幅度问题",
    "内容问题",
    "画面问题",
    "其他",
]

[reject_reasons.post_editing_class1_issues]
name = "转场、剪辑效果"
type = "Label"
options = [
    "过渡转场、剪辑效果类",
    "拼贴、组合成的画面（例如PPT动效、多人视频会议画面）",
    "人脸马赛克等剪辑加工",
]

[reject_reasons.post_editing_class2_issues]
name = "后期合成字幕"
type = "Label"
options = [
    "片头特效、片尾演职人员表等",
    "台词、叙述字幕",
    "后期特效字幕、水印logo、台标、时间戳等",
]

[reject_reasons.motion_issues]
name = "运动幅度问题"
type = "Label"
options = [
    "画面变化幅度过小",
    "完全静止的画面时长超过1秒的部分，需要剪切剔除",
    "（动漫）完全静止帧时长超过片段总时长70%",
]

[reject_reasons.content_issues]
name = "内容问题"
type = "Label"
options = [
    "内容无意义、过分抽象或艺术化",
    "动作或视角混乱、主体不明确导致难以理解视频内容",
    "电脑录屏（录屏部分、软件UI占画面主体）、平面素材（如漫画、照片、报表等）的展示",
]

[reject_reasons.picture_issues]
name = "画面问题"
type = "Label"
options = [
    "光影、色彩问题（画面太暗或太亮以至于看不清内容）",
    "对焦不准、全景深失焦",
    "抖动严重、运动速度过快导致动态模糊",
    "噪点过多、保真度低、画质老旧（例如老式摄像机、监控录像拍摄）",
    "技术问题（解码异常导致帧率异常，画面卡顿、冻结，比例被异常拉伸或压扁）",
]
