[application]
name = "Video Annotation Tool"
version = "1.0.0"
author = "Zulution.AI"
enable_hashsum_validation = true
enable_video_preprocessing = false

[accept_reasons]
_simple = [
    "画面速度",
    "相机运动",
    "场景类型",
    "画面构图",
    "光影、色彩",
    "美学特征",
    "其他",
]

[accept_reasons.motion]
name = "画面速度"
type = "RadioButton"
options = [
    "非常慢速",
    "慢速",
    "中速",
    "快速",
    "非常快速",
    "多种运动速度（非单一类型）",
    "其他速度类型",
]

[accept_reasons.camera_movement]
name = "相机运动"
type = "RadioButton"
options = [
    "固定拍摄",
    "推轨拍摄（镜头沿轨道运动推拉、焦距固定）",
    "变焦拍摄（镜头固定、焦距变化）",
    "推轨变焦拍摄（希区柯克变焦）",
    "水平摇摄 - 向左转动",
    "水平摇摄 - 向右转动",
    "垂直摇摄 - 向上转动",
    "垂直摇摄 - 向下转动",
    "旋转镜头 - 顺时针",
    "旋转镜头 - 逆时针",
    "跟踪镜头",
    "环绕镜头",
    "手持拍摄（非稳定器）",
    "无人机拍摄",
    "复合运动类型（非单一类型）",
    "其他相机运动类型",
]

[accept_reasons.scene]
name = "场景类型"
options = [
    "对话场景",
    "动作场景",
    "环境场景",
    "人物介绍",
    "情感场景",
    "建立镜头",
    "过程记录",
    "其他场景类型",
]

[accept_reasons.composition]
name = "画面构图"
options = [
    "平衡构图，三分、对称、黄金比例等",
    "非平衡构图",
    "视觉重心突出",
    "动态感强（例如利用极端透视或视角形成视觉引导）",
]

[accept_reasons.lighting_color]
name = "光影、色彩"
options = [
    "光影层次丰富",
    "明暗对比强烈",
    "色彩搭配和谐",
    "光影、色彩风格化强烈",
]

[accept_reasons.aesthetic_features]
name = "美学特征"
options = [
    "构图富有美感",
    "镜头运动流畅",
    "画面运动有节奏感",
    "表演自然，情绪突出",
    "环境细节丰富",
    "材质与纹理清晰、富有质感",
    "焦点控制（例如通过前后景虚化形成对比）",
    "其他美学特征",
]

[reject_reasons]
_simple = [
    "转场、剪辑效果",
    "后期合成字幕",
    "运动幅度问题",
    "内容问题",
    "画面问题",
    "其他",
]

[reject_reasons.post_editing_class1_issues]
name = "转场、剪辑效果"
type = "Label"
options = [
    "过渡转场、剪辑效果类",
    "拼贴、组合成的画面（例如PPT动效、多人视频会议画面）",
    "人脸马赛克等剪辑加工",
]

[reject_reasons.post_editing_class2_issues]
name = "后期合成字幕"
type = "Label"
options = [
    "片头特效、片尾演职人员表等",
    "台词、叙述字幕",
    "后期特效字幕、水印logo、台标、时间戳等",
]

[reject_reasons.motion_issues]
name = "运动幅度问题"
type = "Label"
options = [
    "画面变化幅度过小",
    "完全静止的画面时长超过1秒的部分，需要剪切剔除",
    "（动漫）完全静止帧时长超过片段总时长70%",
]

[reject_reasons.content_issues]
name = "内容问题"
type = "Label"
options = [
    "内容无意义、过分抽象或艺术化",
    "动作或视角混乱、主体不明确导致难以理解视频内容",
    "电脑录屏（录屏部分、软件UI占画面主体）、平面素材（如漫画、照片、报表等）的展示",
]

[reject_reasons.picture_issues]
name = "画面问题"
type = "Label"
options = [
    "光影、色彩问题（画面太暗或太亮以至于看不清内容）",
    "对焦不准、全景深失焦",
    "抖动严重、运动速度过快导致动态模糊",
    "噪点过多、保真度低、画质老旧（例如老式摄像机、监控录像拍摄）",
    "技术问题（解码异常导致帧率异常，画面卡顿、冻结，比例被异常拉伸或压扁）",
]
